# Semaphore to decide when the app could start
# Setting to True start imediately at the run of the containers, otherwise when
#   it is changed in the host directory wher eis located this file
start: True 


database:
  directory: "/app/database" 
  users:    
    dbname: "users.db"
  servers:  
    dbname: "server.db"
  pr:  
    dbname: "pr.db"

servers:
  token: 
    token_expiration_days: 30     # days to send chat that token is going to expire
    refreshLinks:
      - name: "git"
        tokenLink: "https://bitbucket-eng-gpk1.cisco.com/bitbucket/plugins/servlet/access-tokens/users/{user_name}/manage"
      - name: "jenkins"
        tokenLink: "https://jenkins-gpk1.cisco.com/user/{user_name}/configure"
  gitServer:    
    timeout: 60
    project: "GAC"

pr:
  polling: 10

# Because this is an internal ip write the domain of the shared netowrk and let docker find the correct if 
#    used by the other app
container_communication:
  host: "CosmFastApi.Cosm-net"
  port: 5000
  secErrorWait: 60
  maxRetryError: 3  # -1  means infinite retry
  maxConnect: 1     # at the moment only one is forced

logs:
  webex-log: "CosmWebex-logfile.log"
  level: "DEBUG"

webexBot:
   token: "NGE1Mjg5NmItZmMyOS00YWI2LThiZTItNDgyZGZlZjA2Zjk2YzY4YTY2NjQtZmU4_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f"
   name: "COSM build"
   uniqueId: "Y2lzY29zcGFyazovL3VzL0FQUExJQ0FUSU9OL2YzMzk3MDAwLTUwN2MtNDg3Zi04ZDkyLWEyZDhiMjUwZThmYw"
   proxy:
     required: True
     proxies:
       https: "http://proxy.esl.cisco.com:80"
       wss: "socks5://proxy.esl.cisco.com:1080"      
